export const Users = [
  {
    id: 1,
    profilePicture:
      "https://i.postimg.cc/Vs31FsDB/Screenshot-20240607-174356.jpg",
    username: "syada",
  },
  {
    id: 9,
    profilePicture: "https://i.postimg.cc/rpk4fQBy/IMG-20231115-WA0074.jpg",
    username: "Hamza Rahiq",
  },
  {
    id: 3,
    profilePicture:
      "https://quranicwisdom.pk/wp-content/uploads/2023/08/20230811095254_fpdl.in_man-reads-book-hotel-room_867452-1033_normal-1-min.jpg",
    username: "Mubashir Qari sahab",
  },
  {
    id: 4,
    profilePicture: "https://i.postimg.cc/BnvkXBY6/IMG-20240913-WA0002.jpg",
    username: "Anas Czn",
  },
  {
    id: 5,
    profilePicture:
      "https://media.istockphoto.com/id/165652387/photo/winner.jpg?s=612x612&w=0&k=20&c=mpYuIlFxXzQcdEmFiNR5ErpWMvLFSacQS_AbbdOACFU=",
    username: "Muneeb Friend",
  },
  {
    id: 10,
    profilePicture: "https://i.postimg.cc/VLdGvxbr/IMG-20230718-WA0002.jpg",
    username: "Waqas Rafiq",
  },
  {
    id: 14,
    profilePicture: "https://i.postimg.cc/1RNVzM3R/waqas-id.jpg",
    username: "waqas naseem",
  },
  {
    id: 7,
    profilePicture: "https://i.postimg.cc/4dvB8YLq/IMG-20240725-WA0011.jpg",
    username: "Owais Rafiq",
  },
  {
    id: 8,
    profilePicture: "https://i.postimg.cc/DzB9xYS1/IMG-20240410-WA0017.jpg",
    username: "Bilal Rafiq",
  },
  {
    id: 6,
    profilePicture:
      "https://thumbs.dreamstime.com/b/man-watching-tv-7657022.jpg",
    username: "Hammad Friend",
  },
  {
    id: 2,
    profilePicture:
      "https://www.shutterstock.com/image-photo/happy-young-man-sitting-home-260nw-2248472067.jpg",
    username: "Shayan Friend",
  },
];

export const Posts = [
  {
    id: 11,
    desc: "Praying for peace and justice for Palestine🤲💘",
    photo:
      "https://img.freepik.com/premium-photo/palestine-with-backdrop-smoke-palestinian-flag_1033529-769.jpg",
    date: "11 month ago",
    userId: 8,
    like: 3932,
    comment: 3029,
  },
  {
    id: 1,
    desc: "pretty girl🥰❤💖",
    photo: "https://i.postimg.cc/ZRqtJqF2/kinaz.jpg",
    date: "5 mins ago",
    userId: 1,
    like: 332,
    comment: 39,
  },
  {
    id: 5,
    desc: " Best moments 💝",
    photo: "https://i.postimg.cc/BZdpZRnn/IMG-20231130-WA0123.jpg",
    date: "1 week ago",
    userId: 10,
    like: 13404,
    comment: 1232,
  },
  {
    id: 11,
    desc: "Port Grand✔",
    photo: "https://i.postimg.cc/Hsx03bpf/waqas-bhai.jpg",
    date: "46 mins ago",
    userId: 14,
    like: 75,
    comment: 40,
  },
  {
    id: 12,
    desc: "Embrace the present, for this life is a gift to be enjoyed💞",
    photo: "https://i.postimg.cc/rmJ9hkKJ/IMG-20240725-WA0011.jpg",
    date: "5 mins ago",
    userId: 7,
    like: 332,
    comment: 39,
  },
  {
    id: 13,
    desc: "MA SHA ALLAH 💖",
    photo: "assets/post/2.jpg",
    date: "15 mins ago",
    userId: 5,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Allah burii nazar se bachay🙌😍.",
    photo: "assets/post/3.jpg",
    date: "1 hour ago",
    userId: 7,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    desc: "MashAllah bro😇.",
    photo: "assets/post/4.jpg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 7,
    desc: "Meri Jaan💖",
    photo: "https://i.postimg.cc/pdPhsn8w/Snapchat-152944592.jpg",
    date: "5 hours ago",
    userId: 7,
    like: 239,
    comment: 35,
  },
  {
    id: 6,
    desc: "Hatred For None.",
    photo: "https://i.postimg.cc/V64LyD29/IMG-20230724-155150.jpg",
    date: "1 day ago",
    userId: 8,
    like: 44,
    comment: 6,
  },
  {
    id: 10,
    desc: "Never regret anything that made you smile.",
    photo: "assets/post/2.jpg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    desc: "Mera Pyara Bhanja 💖",
    photo: "assets/post/3.jpg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Nice smile 🥰💋.",
    photo: "assets/post/4.jpg",
    date: "5 days ago",
    userId: 1,
    like: 11,
    comment: 2,
  },
];
